# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: churn.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'churn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hurn.proto\x12\x05\x63hurn\"N\n\x08\x46\x65\x61tures\x12\x0e\n\x06gender\x18\x01 \x01(\t\x12\x19\n\x11subscription_type\x18\x02 \x01(\t\x12\x17\n\x0f\x63ontract_length\x18\x03 \x01(\t\" \n\x0fPredictResponse\x12\r\n\x05\x63hurn\x18\x01 \x01(\x05\x32\x42\n\x0c\x43hurnService\x12\x32\n\x07Predict\x12\x0f.churn.Features\x1a\x16.churn.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'churn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATURES']._serialized_start=22
  _globals['_FEATURES']._serialized_end=100
  _globals['_PREDICTRESPONSE']._serialized_start=102
  _globals['_PREDICTRESPONSE']._serialized_end=134
  _globals['_CHURNSERVICE']._serialized_start=136
  _globals['_CHURNSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
