// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: churn.proto

package churnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChurnService_Predict_FullMethodName = "/churn.ChurnService/Predict"
)

// ChurnServiceClient is the client API for ChurnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChurnServiceClient interface {
	Predict(ctx context.Context, in *Features, opts ...grpc.CallOption) (*PredictResponse, error)
}

type churnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChurnServiceClient(cc grpc.ClientConnInterface) ChurnServiceClient {
	return &churnServiceClient{cc}
}

func (c *churnServiceClient) Predict(ctx context.Context, in *Features, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, ChurnService_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChurnServiceServer is the server API for ChurnService service.
// All implementations must embed UnimplementedChurnServiceServer
// for forward compatibility
type ChurnServiceServer interface {
	Predict(context.Context, *Features) (*PredictResponse, error)
	mustEmbedUnimplementedChurnServiceServer()
}

// UnimplementedChurnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChurnServiceServer struct {
}

func (UnimplementedChurnServiceServer) Predict(context.Context, *Features) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedChurnServiceServer) mustEmbedUnimplementedChurnServiceServer() {}

// UnsafeChurnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChurnServiceServer will
// result in compilation errors.
type UnsafeChurnServiceServer interface {
	mustEmbedUnimplementedChurnServiceServer()
}

func RegisterChurnServiceServer(s grpc.ServiceRegistrar, srv ChurnServiceServer) {
	s.RegisterService(&ChurnService_ServiceDesc, srv)
}

func _ChurnService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Features)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChurnServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChurnService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChurnServiceServer).Predict(ctx, req.(*Features))
	}
	return interceptor(ctx, in, info, handler)
}

// ChurnService_ServiceDesc is the grpc.ServiceDesc for ChurnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChurnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "churn.ChurnService",
	HandlerType: (*ChurnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _ChurnService_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "churn.proto",
}
